version: '3.4'

services:
  authenticationservice:
    image: ${DOCKER_REGISTRY-}authenticationservice
    build:
      context: .
      dockerfile: AuthenticationService/Dockerfile
    depends_on:
      - "db"
  helloworld:
    image: ${DOCKER_REGISTRY-}helloworld
    build:
      context: .
      dockerfile: HelloWorld/Dockerfile
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432"
  adminer:
    image: adminer
    ports:
      - "8080"